// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCIH-FircSWODcAWJZK2d971b9IqzvbWQ',
    appId: '1:180429637069:web:67244a14e6fe38a457f084',
    messagingSenderId: '180429637069',
    projectId: 'braita-cf3e7',
    authDomain: 'braita-cf3e7.firebaseapp.com',
    storageBucket: 'braita-cf3e7.firebasestorage.app',
    measurementId: 'G-DGCQW60LMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRd9b-fP4TXnmA-VE5RsJUQjukQrlnhY',
    appId: '1:180429637069:android:f27f5137b4983b3d57f084',
    messagingSenderId: '180429637069',
    projectId: 'braita-cf3e7',
    storageBucket: 'braita-cf3e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqPTuZq4fPqb0ALnWsmascTmcvI4OzrI',
    appId: '1:180429637069:ios:711091ce9a7a4b9357f084',
    messagingSenderId: '180429637069',
    projectId: 'braita-cf3e7',
    storageBucket: 'braita-cf3e7.firebasestorage.app',
    iosBundleId: 'com.example.braitaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqPTuZq4fPqb0ALnWsmascTmcvI4OzrI',
    appId: '1:180429637069:ios:711091ce9a7a4b9357f084',
    messagingSenderId: '180429637069',
    projectId: 'braita-cf3e7',
    storageBucket: 'braita-cf3e7.firebasestorage.app',
    iosBundleId: 'com.example.braitaNew',
  );
}
